CREATE DATABASE funfact_db;

DROP TABLE facts;

CREATE TABLE facts
(
    fact_id  INT PRIMARY KEY,
    facts VARCHAR,
    status BOOLEAN
);


INSERT INTO facts (fact_id, facts, status) VALUES
(1, 'Meteorologists claim they`re right 85% of the time (think about that one!)', true),
(2, 'On the ground, a group of geese is a gaggle, in the sky it is a skein.', false),
(3, 'Ants closely resemble human manners: When they wake, they stretch & appear to yawn in a human manner before taking up the tasks of the day.', true),
(4, 'The three most recognized Western names in China are Jesus Christ, Richard Nixon, & Elvis Presley.', true),
(5, 'The verb "cleave" is the only English word with two synonyms which are antonyms of each other: adhere and separate.', false),
(6, 'There are 1,792 steps in the Eiffel Tower', false),
(7, 'Ingrown toenails are hereditary.', true),
(8, 'Mr. Rogers is an ordained minister.', true),
(9, 'The average lifespan of an eyelash is five months.', false),
(10, 'The human heart creates enough pressure to squirt blood 30ft.', true),
(11, 'The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.', false),
(12, 'When the University of Nebraska Cornhuskers play football at home, the stadium becomes the state`s third largest city.', true),
(13, 'Nearly 80% of all animals on earth have six legs.', false),
(14, 'Months that begin on a Sunday will always have a `Friday the 13th`.', true),
(15, '38% of American men say they love their cars more than women', false),
(16, 'In The Empire Strikes Back there is a potato hidden in the asteroid field', false),
(17, 'Non-dairy creamer is flammable.', false),
(18, 'Two-thirds of the world`s eggplant is grown in New Jersey.', true),
(19, 'A raisin dropped in a glass of fresh champagne will bounce up and down continually from the bottom of the glass to the top.', true),
(20, 'Venus is the only planet that rotates clockwise.', true),
(21, 'The Black Death reduced the population of Europe by one third in the period from 1347 to 1351.', true),
(22, 'The thumbnail grows the slowest, the middle nail the fastest, nearly 4 times faster than toenails.', false),
(23, 'Shakespeare invented the word `assassination` and `bump`.', false),
(24, '2,000 pounds of space dust and other space debris fall on the Earth every day.', false),
(25, 'Texas is also the only state that is allowed to fly its state flag at the same height as the U.S. flag.', true),
(26, 'In Aspen Colorado, you can have a maximum income of $104,000 and still receive government subsidized housing.', false),
(27, 'The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.', true),
(28, 'Average life span of a major league baseball: 7 pitches.', false),
(29, 'You spend 7 years of your life in the bathroom.', true),
(30, 'The state of Florida is bigger than England!', true),
(31, 'Women manage the money and pay the bills in 75% of all Americans households.', false),
(32, 'The world record for spitting a watermelon seed is 65 feet 4 inches.', true),
(33, 'The S in Harry S. Truman did not stand for anything.', false),
(34, 'More people are killed annually by donkeys than airplane crashes.', false),
(35, 'Fictional/horror writer Stephen King sleeps with a nearby light on to calm his fear of the dark.', false),
(36, 'During a severe windstorm or rainstorm the Empire State Building sways several feet to either side.', true),
(37, 'One third of all cancers are sun related.', true),
(38, 'Women blink nearly twice as much as men.', true),
(39, 'You burn more calories sleeping than you do watching TV.', true),
(40, 'Arnold Schonberg suffered from triskaidecaphobia, the fear of the number 13. He died at 13 minutes from midnight on Friday the 13th.', false),
(41, 'Some lions mate over 50 times a day.', true),
(42, 'There is approximately one chicken for every human being in the world.', true),
(43, 'The average person spends 12 weeks a year `looking for things`.', false),
(44, 'CBS` "60 Minutes" is the only TV show without a theme song/music.', false),
(45, 'The longest recorded flight of a chicken is thirteen seconds.', true),
(46, 'A dragonfly has a lifespan of 24 hours.', true),
(47, 'A dime has 118 ridges around the edge.', false),
(48, 'On average, people fear spiders more than they do death.', false),
(49, 'Shakespeare spelled his OWN name several different ways.', true),
(50, 'In 1980, a Las Vegas hospital suspended workers for betting on when patients would die.', false),
(51, 'Butterflies taste with their hind feet.', false),
(52, 'Dr. Jack Kevorkian first patient has Alzheimer`s disease.', true),
(53, 'In England, the Speaker of the House is not allowed to speak.', false),
(54, 'Sex burns 360 calories per hour.', false),
(55, 'NBA superstar Michael Jordan was originally cut from his high school basketball team.', false),
(56, 'Bats always turn left when exiting a cave', false),
(57, 'Babies are born without kneecaps. They don`t appear until the child reaches 2-6 years of age.', true),
(58, 'Americans travel 1,144,721,000 miles by air every day', true),
(59, 'Length of beard an average man would grow if he never shaved 27.5 feet', true),
(60, 'The highest per capita Jell-O consumption in the US is Des Moines.', false),
(61, 'Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.', true),
(62, 'Every year 11,000 Americans injure themselves while trying out bizarre sexual positions.', true),
(63, 'Golf courses cover 4% of North America.', true),
(64, 'Maine is the only state whose name is just one syllable.', false),
(65, 'You can`t kill yourself by holding your breath.', false),
(66, 'In the United States, a pound of potato chips costs two hundred times more than a pound of potatoes.', false),
(67, 'A piece of paper can be folded no more than 9 times.', false),
(68, 'Conception occurs most in the month of December.', true),
(69, 'Alfred Hitchcock didn`t have a belly button. It was eliminated when he was sewn up after surgery.', true),
(70, '10,000 Dutch cows pass through the Amsterdam airport each year.', true),
(71, 'Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning "containing arsenic."', false),
(72, 'Elephants are the only animals that can`t jump.', false),
(73, 'Starfish haven`t got brains.', false),
(74, 'Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.', true),
(75, 'Donald Duck`s middle name is Fauntleroy.', true),
(76, 'All of the clocks in the movie "Pulp Fiction" are stuck on 4:20, a national pot-smokers hour.', false),
(77, 'A snail can sleep for three years.', false),
(78, 'There is a town in Newfoundland, Canada called Dildo.', false),
(79, 'There are 293 ways to make change for a dollar.', false),
(80, '166,875,000,000 pieces of mail are delivered each year in the US', false),
(81, 'There are no clocks in Las Vegas gambling casinos.', true),
(82, 'A jellyfish is 95 percent water!', true),
(83, 'Dr. Kellogg introduced Kellogg`s Corn Flakes in hopes that it would reduce masturbation.', false),
(84, 'Spain leads the world in cork production', true),
(85, 'The buzz from an electric razor in America plays in the key of B flat; Key of G in England.', false),
(86, 'There are 336 dimples on a regulation golf ball.', true),
(87, 'The dot over the letter `i` is called a tittle.', false),
(88, 'A shark is the only fish that can blink with both eyes.', true),
(89, '5,840 people with pillow related injuries checked into U.S. emergency rooms in 1992.', false),
(90, 'John Lennon`s first girlfriend was named Thelma Pickles.', true),
(91, 'The Great Wall of China is the only man-made structure visible from space.', false),
(92, 'In the last 3,500 years, there have been approximately 230 years of peace throughout the civilized world.', false),
(93, 'The fingerprints of koala bears are virtually indistinguishable from those of humans, so much so that they can be easily confused at a crime scene.', false),
(94, 'Right-handed people live, on average; nine years longer than left handed people.', false),
(95, 'Honey is the only food which does not spoil.', true),
(96, 'The storage capacity of human brain exceeds 4 Terabytes.', true),
(97, 'The name Wendy was made up for the book "Peter Pan."', true),
(98, 'The longest one-syllable word in the English language is "screeched."', true),
(99, 'A bull can inseminate 300 cows from one single ejaculation.', true),
(100, 'Over 1000 birds a year die from smashing into windows!', false),
(101, 'When a Hawaiian woman wears a flower over her left ear, it means that she is not available.', false),
(102, 'In the Philippine jungle, the yo-yo was first used as a weapon.', true),
(103, 'Mike Nesmith`s (the guitarist of The Monkeys) mom invented White Out.', true),
(104, 'Cats have over one hundred vocal sounds, while dogs only have about ten.', true),
(105, 'The very first bomb dropped by the Allies on Berlin during World War II Killed the only elephant in the Berlin Zoo.', false),
(106, 'Mount Olympus Mons on Mars is three times the size of Mount Everest.', false),
(107, 'Only 6 people in the whole world have died from moshing.', true),
(108, 'Thomas Edison, acclaimed inventor of the light bulb, was afraid of the dark.', false),
(109, 'The praying mantis is the only insect that can turn its head.', true),
(110, 'The letters KGB stand for Komitet Gosudarstvennoy Bezopasnosti.', false),
(111, 'One quarter of the bones in your body are in your feet.', true),
(112, 'The 3 most valuable brand names on earth are Marlboro, Coca-Cola, and Budweiser (in that order).', false),
(113, 'Winston Churchill was born in a ladies` room during a dance.', false),
(114, 'A cat has 32 muscles in each ear.', true),
(115, 'Daffy Duck`s middle name is "Dumas."', true),
(116, 'You can be fined up to $1,000 for whistling on Sunday in Salt Lake City, Utah.', false),
(117, 'Most lipstick contains fish scales!', false),
(118, 'Most Egyptians died by the time they were 30 about 300 years ago.', true),
(119, 'Kelsey Grammar sings and plays the piano for the theme song of Fraiser.', true),
(120, 'There are 1 million ants for every human in the world.', false);

SELECT * FROM facts;
